[Cache]
    # 生成的验证码
    [Cache.Verify]
        # 验证码
        Code = "Verify:Code"
    [Cache.SysLoggerOperate]
        # 后台操作日志队列
        Queue = "SysLoggerOperate:Queue"
    [Cache.SysMenu]
        # 后台菜单模块名称
        Module = "SysMenu:Module"
        # 后台菜单权限
        Code = "SysMenu:Code"
    [Cache.SysLoginLog]
        # 后台登录日志队列
        Queue = "SysLoginLog:Queue"
    [Cache.SysUser]
        # 后台用户权限
        Code = "SysUser:Code::UserId"

